export const TAXONOMY = [
  {id:"monocoque",name:"MONOCOQUE",code:"01",description:"Objets manufacturés, transportables et manipulables. Monocoque, lisse, biomimétique.",subcategories:[
    ["Véhicules Terrestres",["Voitures, berlines, SUV, sportives, concept-cars","Motos, scooters, hoverbikes, motos lévitantes","Vélos, vélos électriques, vélos monocoques, vélos biomécaniques"]],
    ["Véhicules Aériens",["Avions, jets, avions furtifs, avions solaires","Hélicoptères, drones, quadricoptères, drones de livraison","Taxis volants, navettes aériennes, capsules volantes"]],
    ["Véhicules Spatiaux",["Vaisseaux spatiaux, navettes, capsules orbitales","Stations spatiales mobiles, vaisseaux-mères","Vaisseaux interstellaires, générationnels, colonisateurs"]],
    ["Véhicules Maritimes & Sous-marins",["Bateaux, yachts, voiliers, catamarans","Sous-marins, submersibles, capsules de plongée","Hydroptères, hovercrafts, véhicules amphibies"]],
    ["Outils Manuels & Électriques",["Marteaux, tournevis, clés, pinces, tenailles","Perceuses, scies, meuleuses, ponceuses","Outils de précision, outils quantiques, outils bio-photoniques"]],
    ["Armes & Défense",["Armes blanches, armes à feu, armes énergétiques","Boucliers, armures, exosquelettes de combat","Systèmes de défense automatisés, drones de combat"]],
    ["Appareils Électroniques & Numériques",["Ordinateurs, laptops, serveurs, supercalculateurs","Téléphones, smartphones, tablettes, phablettes","Écrans, projecteurs holographiques, interfaces neurales"]],
    ["Objets du Quotidien",["Mobilier, tables, chaises, lits, canapés","Ustensiles de cuisine, vaisselle, électroménager","Luminaires, objets de décoration, objets personnels"]],
    ["Vêtements & Accessoires",["Vêtements, chaussures, sacs, bijoux","Lunettes connectées, casques, montres","Gants, ceintures, écharpes, cravates"]],
    ["Énergie & Ressources",["Générateurs, alternateurs, dynamos","Batteries, piles, accumulateurs, supercondensateurs","Réacteurs nucléaires, fusion, quantiques"]],
    ["Modules & Structures Mobiles",["Modules monocoques, modules habitables","Conteneurs, capsules, pods, cubes modulaires","Bases mobiles, laboratoires mobiles, stations de recharge"]],
    ["Instruments Scientifiques & Médicaux",["Microscopes, télescopes, spectromètres, analyseurs","Scanners, IRM, échographes, radiographies","Robots chirurgicaux, prothèses, implants"]],
    ["Objets Artistiques & Culturels",["Instruments de musique, synthétiseurs","Œuvres d'art, sculptures, peintures, installations","Livres, manuscrits, artefacts"]],
    ["Objets de Sport & Loisirs",["Ballons, raquettes, battes, clubs","Vélos de sport, skates, rollers, trottinettes","Jouets, figurines, équipements de camping"]],
    ["Objets de Communication",["Antennes, radars, satellites de communication","Radios, émetteurs, récepteurs","Balises, bornes Wi-Fi, relais, répéteurs"]],
    ["Robots & Automates",["Robots industriels, bras robotisés","Robots domestiques, robots humanoïdes","Drones autonomes, robots explorateurs, IA incarnées"]],
    ["Objets Connectés & IoT",["Capteurs, température, mouvement, lumière","Actionneurs, moteurs, servomoteurs","Réseaux maillés, interfaces haptiques"]],
    ["Objets de Construction & Bricolage",["Matériaux, briques, ciment, bois, acier, verre","Échafaudages, coffrages, grues, nacelles","Modules préfabriqués, structures démontables"]],
    ["Objets Alimentaires & Cuisine",["Aliments, fruits, légumes, viandes, céréales","Boissons, eau, jus, cafés","Emballages, conteneurs, rations"]],
    ["Objets de Santé & Bien-être",["Médicaments, dispositifs médicaux","Exosquelettes médicaux, prothèses avancées","Fitness, produits de soin"]]
  ]},
  {id:"humanite",name:"HUMANITÉ 2126",code:"02",description:"Êtres humains, personnages et entités humanoïdes. Silhouettes élancées, combinaisons blanches, interfaces neurales.",subcategories:[
    ["Humains par Âge",["Bébés, nourrissons, nouveau-nés","Enfants, adolescents, jeunes adultes","Adultes, personnes âgées, transhumanistes"]],
    ["Humains par Genre",["Hommes, femmes, non-binaires","Androgynes, genderfluid, agenres","Intersexués, transgenres"]],
    ["Humains par Profession",["Scientifiques, chercheurs, professeurs","Médecins, ingénieurs, architectes, techniciens","Pilotes, artistes, explorateurs, entrepreneurs"]],
    ["Humains par Culture & Ethnie",["Cultures africaines, asiatiques, européennes","Cultures américaines, océaniennes, arctiques","Cultures urbaines, rurales, tribales"]],
    ["Personnages Augmentés",["Implants neuraux, interfaces cerveau-machine","Prothèses bioniques, membres artificiels","Augmentations cognitives, sensorielles et physiques"]],
    ["Cyborgs & Hybrides",["Cyborgs partiels, cyborgs complets","Hybrides humain-animal, humain-machine","Hybrides humain-végétal, humain-IA"]],
    ["Androïdes & Robots Humanoïdes",["Androïdes de compagnie, de travail, de combat","Gynoïdes, androgynes synthétiques","Robots humanoïdes, réplicants, synthétiques"]],
    ["Clones & Mutants",["Clones parfaits, clones défectueux","Mutants, super-héros, super-vilains","Êtres génétiquement modifiés, chimères"]],
    ["Groupes & Organisations",["Familles, clans, tribus","Équipes, escouades, unités","Corporations, gouvernements, ONG, mouvements"]],
    ["Vêtements & Combinaisons",["Combinaisons techniques monopièces","Tenues de travail, cérémonie, sport, combat","Tenues spatiales, médicales, de protection"]],
    ["Accessoires & Bijoux",["Lunettes, visières, casques","Montres, bracelets, bagues","Colliers, sacs, chaussures techniques"]],
    ["Expressions & Postures",["Visages, joie, tristesse, colère, peur","Mains, gestes, signes","Postures, mouvements, regards"]],
    ["États & Conditions",["En bonne santé, blessé, malade","Éveillé, endormi, inconscient","Calme, stressé, en colère, heureux, triste"]],
    ["Personnages Mythiques & Légendaires",["Dieux, déesses, demi-dieux","Héros, prophètes, sorciers","Vampires, anges, démons, esprits"]]
  ]},
  {id:"biomimicry",name:"BIOMIMICRY",code:"03",description:"Faune, flore et créatures non humaines. Biomécanique douce, titane, fibres optiques, lentilles bleu roi.",subcategories:[
    ["Mammifères",["Félins, lions, tigres, léopards, chats","Canidés, loups, chiens, renards","Herbivores, primates, cétacés, marsupiaux"]],
    ["Oiseaux",["Rapaces, aigles, faucons, hiboux","Passereaux, échassiers, palmipèdes","Colibris, perroquets, autruches, manchots"]],
    ["Reptiles & Amphibiens",["Serpents, pythons, cobras, vipères","Lézards, iguanes, geckos, caméléons","Tortues, crocodiles, grenouilles, salamandres"]],
    ["Poissons & Créatures Marines",["Poissons osseux et cartilagineux","Créatures abyssales, méduses, cténophores","Pieuvres, coraux, anémones, oursins"]],
    ["Insectes & Arachnides",["Coléoptères, scarabées, coccinelles","Papillons, abeilles, fourmis, libellules","Araignées, scorpions, mille-pattes"]],
    ["Crustacés & Mollusques",["Crabes, homards, crevettes","Escargots, limaces, bivalves","Gastéropodes marins, coquillages"]],
    ["Vers & Micro-organismes",["Vers de terre, vers marins","Nématodes, plathelminthes","Bactéries, virus, protozoaires, levures"]],
    ["Créatures Biomécaniques",["Squelette de titane visible","Derme de fibres optiques, nageoires évasées","Yeux lentille bleu roi, propulsion magnétique, camouflage"]],
    ["Hybrides Animal-Machine",["Animaux robotisés, drones animaliers","Animaux augmentés, prothèses animales","Animaux cyborgs, essaims biomimétiques"]],
    ["Plantes & Végétaux",["Arbres, fleurs, arbustes, herbes","Algues, plantes aquatiques, désertiques, tropicales","Plantes bioluminescentes, géantes, carnivores"]],
    ["Champignons & Lichens",["Champignons comestibles, vénéneux, médicinaux","Lichens, mousses symbiotiques","Mycorhizes, réseaux fongiques"]],
    ["Écosystèmes",["Forêts, jungles, savanes, prairies","Déserts, océans, lacs, rivières","Montagnes, récifs, grottes, îles"]],
    ["Créatures Mythiques & Légendaires",["Dragons, drakes, wyvernes","Licornes, phénix, griffons, sirènes","Kraken, hydres, chimères, esprits"]],
    ["Animaux Préhistoriques",["Dinosaures, vélociraptors, tricératops","Ptérosaures, mammouths, smilodons","Mégalodons, plésiosaures, insectes géants"]],
    ["Animaux Domestiques",["Chiens, chats, oiseaux de compagnie","Poissons d'aquarium, rongeurs","Reptiles et animaux de ferme de compagnie"]],
    ["Animaux de Ferme",["Vaches, moutons, chèvres","Cochons, poulets, canards, dindes","Chevaux, ânes, lapins, abeilles"]],
    ["Animaux Sauvages",["Animaux des forêts et savanes","Animaux des déserts et montagnes","Animaux polaires, marins et volants"]]
  ]},
  {id:"architectural",name:"ARCHITECTURAL",code:"04",description:"Bâtiments, infrastructures, paysages et environnements. Tours monocoques, dômes, stations toriques, rubans supraconducteurs.",subcategories:[
    ["Bâtiments Résidentiels",["Maisons, pavillons, villas","Immeubles, appartements, tours","Habitats troglodytes, flottants, nomades"]],
    ["Bâtiments Commerciaux",["Bureaux, sièges sociaux, centres commerciaux","Boutiques, marchés, restaurants, cafés","Hôtels, banques, entrepôts, parkings"]],
    ["Bâtiments Industriels",["Usines, manufactures, fabriques","Raffineries, centrales, mines, carrières","Entrepôts logistiques, silos, parcs technologiques"]],
    ["Bâtiments Institutionnels",["Écoles, universités, campus","Hôpitaux, bibliothèques, musées","Théâtres, stades, tribunaux, ministères"]],
    ["Bâtiments Religieux",["Églises, cathédrales, basiliques","Mosquées, synagogues, temples","Monastères, sanctuaires, mémoriaux"]],
    ["Bâtiments Militaires",["Forteresses, citadelles","Bunkers, bases militaires, camps","Tours de guet, arsenaux, centres de commandement"]],
    ["Architecture Futuriste",["Tours monocoques monolithiques","Stations spatiales toriques, dômes fumés","Structures lévitantes, arcologies, biosphères"]],
    ["Infrastructures de Transport",["Routes, autoroutes, ponts, viaducs","Tunnels, rails, monorails, gares","Aéroports, ports, rubans supraconducteurs, ascenseurs spatiaux"]],
    ["Infrastructures Énergétiques",["Centrales électriques, parcs éoliens","Barrages, fermes solaires, réseaux électriques","Stations de recharge, réacteurs à fusion"]],
    ["Infrastructures de Communication",["Antennes, relais, tours","Satellites, stations au sol, fibres optiques","Data centers, réseaux maillés, clouds"]],
    ["Paysages Naturels",["Montagnes, vallées, canyons, plateaux","Forêts, jungles, savanes, déserts","Océans, lacs, rivières, glaciers, récifs"]],
    ["Paysages Urbains",["Villes, métropoles, mégapoles","Quartiers, CBD, zones industrielles","Parcs, places, rues, galeries, rooftops"]],
    ["Paysages Agricoles",["Champs, cultures, labours","Vergers, rizières, plantations","Fermes, pâturages, serres, élevages"]],
    ["Paysages Souterrains",["Grottes, cavernes, gouffres","Mines, galeries, tunnels","Réseaux souterrains, bunkers, cités souterraines"]],
    ["Paysages Extrêmes",["Arctique, Antarctique, pôles","Déserts, volcans, fonds marins","Espace, Lune, Mars, astéroïdes, nébuleuses"]],
    ["Paysages Imaginaires",["Paysages oniriques et surréalistes","Paysages post-apocalyptiques, utopiques, dystopiques","Paysages fantastiques, science-fiction, abstraits"]],
    ["Éléments Naturels",["Ciels, nuages, brumes, aurores","Tempêtes, orages, éclairs, tornades","Eau, feu, terre, air, halos"]],
    ["Aménagements & Jardins",["Parcs, jardins, squares","Fontaines, bassins, statues, monuments","Passerelles, terrasses, jardins suspendus"]],
    ["Architecture Intérieure",["Pièces, chambres, salons, cuisines","Couloirs, escaliers, ascenseurs, halls","Fenêtres, portes, plafonds, sols, murs"]],
    ["Lieux de Mémoire & Patrimoine",["Ruines, vestiges, sites archéologiques","Monuments, mémoriaux, musées de site","Villes historiques, parcs nationaux, réserves"]]
  ]}
].map(c=>({...c,subcategories:c.subcategories.map((s,i)=>({id:`${c.id}-${i+1}`,name:s[0],items:s[1]}))}));
export const TAXONOMY_COUNTS={categories:4,subcategories:71,sourceAssetGroups:527};
export const allSubcategories=()=>TAXONOMY.flatMap(c=>c.subcategories.map(s=>({...s,category:c.name,categoryId:c.id})));
